# Generated by Django 4.1.2 on 2025-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('HISTORICAL_FICTION', 'Historical Fiction'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('HORROR', 'Horror'), ('ADVENTURE', 'Adventure'), ('YA', 'Young Adult'), ('CHILDRENS', "Children's Fiction"), ('POETRY', 'Poetry'), ('SELF_HELP', 'Self-Help'), ('PHILOSOPHY', 'Philosophy'), ('TRUE_CRIME', 'True Crime'), ('SCIENCE', 'Science'), ('HEALTH_WELLNESS', 'Health & Wellness'), ('ART_PHOTOGRAPHY', 'Art & Photography'), ('BUSINESS_ECONOMICS', 'Business & Economics'), ('COOKING_FOOD', 'Cooking/Food'), ('TRAVEL', 'Travel'), ('RELIGION_SPIRITUALITY', 'Religion & Spirituality'), ('POLITICS', 'Politics'), ('PSYCHOLOGY', 'Psychology'), ('DRAMA', 'Drama'), ('GRAPHIC_NOVELS', 'Graphic Novels/Comics'), ('WESTERN', 'Western')], max_length=50)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('average_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
