# Generated by Django 5.2 on 2025-04-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_genre_remove_userprofile_reviewed_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
    ]
