# Generated by Django 5.2 on 2025-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_remove_userprofile_recently_viewed_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Young Adult', 'Young Adult')], max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='livres.usergenre'),
        ),
    ]
